lib/mysql/mysql.go
modules/mysql.go
tls.go

**What it does**: Per @dadrian's comments in #23, there is no good reason for the `net.Conn`'s to be stored as pointers (and OTOH storing them as pointers leads to some very awkward code)
**How to test it**: Just run the integration tests

remove unnecessary indirection on net.Conn

---

cmd/zgrab2/main.go
module.go
utility.go

Interfaces are effectively already pointers, see
https://research.swtch.com/interfaces.

Remove pointer-to-interface in zgrab2 framework

---

README.md

This just adds some preliminary information on how to run integration tests. It might not be perfect - I was just going by what I saw in the Travis build logs.
Exactly 😉 
_N/A_
Fixes #50

Add information on running integration tests to README.md

---

lib/ssh/kex.go
lib/ssh/kex_gex.go
lib/ssh/keys.go

This is the first step towards removing the dependency on zgrab.
Same way as always.
*Note: I'm sure y'all are on it without me mentioning it, but we should wait until Travis runs the integration tests here... I was having issues getting the integration tests to complete successfully even from a clean build (I'll make an issue for that).*
Unfortunately, even without these changes there will still be nested dependencies on the original `zgrab/ztools/keys` package through `github.com/zmap/zcrypto` https://godoc.org/github.com/zmap/zgrab/ztools/keys?importers
Changes will be needed to zcrypto to fully remove the dependency on zgrab.
Doesn't fully fix #48, but this at least starts to address it.

Changed tools/keys dependencies to point to zgrab2.

---

integration_tests/ftp/setup.sh
integration_tests/mysql/setup.sh
integration_tests/postgres/setup.sh
integration_tests/setup.sh
integration_tests/ssh/setup.sh
integration_tests/test.sh

Previously, the integration tests worked as follows:
1. Run the `setup.sh` for each module -- starting up one or more containers for it
2. Run the `test.sh` for each module, hitting those containers
3. Validate the output of the modules
4. Run the `cleanup.sh` for each module
This was convenient, since you could skip steps 1 & 3 to repeatedly run the tests; also, it also had the side effect of giving plenty of time for most of the containers to come up before they needed to be used (while the others were being started).
But, as the number of containers grows, this becomes less tractable. This PR changes the behavior to
1. For each module:
a. Run its `setup.sh`
b. Run its `test.sh`
c. Run its `cleanup.sh`
2. Validate the output
There is a new flag (`NOSETUP`) that will allow you to keep …

Use fewer simultaneous containers

---

README.md

This is a small change to the `README`. I'm honestly not sure if this is incorrect documentation or not since _technically_ zgrab2 has zgrab as a dependency so you _can_ go into the old zmap directory and build it.
But my guess was that y'all meant to reference the new version?
No changes
None
Didn't think this really deserved an issue 😄

Fix README install instructions pointing to previous versions of zgrab

---

.gitignore
Makefile
integration_tests/mysql/setup.sh
integration_tests/mysql/test.sh
integration_tests/postgres/setup.sh

Removes the integration-test-setup target. Setup will now be per-module, rather than all up front (to cut down on the number of containers that need to be running simultaneously).
Run `make integration-test` (or watch Travis do so) -- it should still work; it used to have `.integration-test-setup` as a dependency, but now it does not.
This is part of the larger task of refactoring the integration tests to require fewer simultaneous running containers.
The destination branch (https://github.com/zmap/zgrab2/pull/46) updates the test scripts, while this actually removes the call to `integration-tests/setup.sh` from the `integration-test` target.

remove integration test setup

---

integration_tests/.template/README.md
integration_tests/.template/cleanup.sh
integration_tests/.template/schema.py
integration_tests/.template/setup.sh
integration_tests/.template/test.sh
integration_tests/new.sh

Move inline scripts in new.sh into templates folder.
Update templates to match most common scenarios.
Either use `new.sh` to create a real new module, or
1. in `integration-tests` run `./new.sh testmod`
2. Modify `integration-tests/testmod/setup.sh`: set `CONTAINER_TAG` to `zgrab_ftp`, and 
3. Modify `integration-tests/testmod/test.sh`: on line 16, replace to `testmod` param to `docker-run.sh` with `ftp`
4. Add the following afterwards: `sed -i 's/"ftp"/"testmod"/g' $OUTPUT_FILE`
5. Run `make integration-test` -- both the test and schema validation should succeed.
None
Part of reducing the number of containers running simultaneously -- the new templates fit the refactored test flow better

Update integration test script templates

---

errors.go
modules/tls.go

This module just uses zgrab2.BaseTLSFlags to implement a simple TLS
module.
I haven't updated TravsCI or added any integration tests yet. I'm wondering if they should really be HTTP(S) tests. @justinbastress, thoughts?
I'm not sure what an HTTPS scan that actually fetches a page would look like under the current framework. Is `zgrab tls` going to do this, or is there some way to combine `zgrab http` and `zgrab tls`, or do we need to add a `zgrab https`? Regardless of what we choose to do with that, we'll still probably want just a raw TLS handshake mode that can be run on any port, since many protocols (that we might not implement immediately) begin with a TLS handshake (e.g. IMAPS, POP3S, etc.)

Implement TLS module

---

docker-runner/Makefile

Previously, a failed `make docker-runner` would continue merrily along, either with no docker-runner or worse, with an out-of-date one.
The problem was, on failure, it needed to clean up a *.id file -- but the successful exit code from `rm` was clobbering the failing exit code from `docker build`.
Remove `docker` from your path, then run `make docker-runner`.
Before the fix, it will pass.
After the fix, it will fail.

if `docker build` fails, fail the build after deleting the *.id file

---

modules/mssql/connection.go
modules/mssql/scanner.go

* re-export MSSQL primitives, remove stuttering `mssql.mssqlXYZ`  names
* re-run golint / gofmt
* add package godocs
* add detailed scan docs
* bugfixes:
* populate InstanceName in result
* fix return value in case of failed / incomplete detection
* add default EncryptMode
`TEST_MODULES=mssql make integration-test`
* Confirm that InstanceName is set
* Point to a non-mssql service, like HTTP, and confirm that it returns a nil result

Update MSSQL GoDocs

---

integration_tests/.template/module/scanner.go

Change 
> _"Package #{MODULE_NAME} provides a zgrab2 module that **proves** for #{MODULE_NAME}"_
to
> _"Package #{MODULE_NAME} provides a zgrab2 module that **scans** for #{MODULE_NAME}"_

Fix typo in scanner template

---

.travis.yml
Makefile

* Added phony `test` Makefile target
* Make travis run the `test` target before getting into the much longer integration tests
Run `make test`, or kick off a travisci build.

Make travis run unit tests

---

lib/mysql/mysql.go
output.go
output_test.go

Rather than letting each module implement its own function to map a flags bit field into a `map[string]bool{'flag1': true, ...}` + `unknowns []uint64`, provide a shared implementation.
Dropped this in a new file, output.go, which would presumably have other utility functions for formatting output in a database/search-friendly way.
This is used in the mysql module, so `TEST_MODULE=mysql make integration-test` should confirm that everything is still working as expected. `go test` will also run some rudimentary sanity checks.

Add shared FlagsToSet function in output.go

---

cmd/zgrab2/main.go
utility.go

Imported https://github.com/ajholland/zflags into https://github.com/zmap/zflags; this PR updates references from the former to the latter.
`make test`, or `make && cmd/zgrab2/zgrab2 --help`.

pull zflags from the zmap project

---

tls.go

This was originally copied from https://github.com/zmap/zgrab/blob/master/zlib/grabber.go#L595, but that actually references zgrab's own `CheckHeartbleed` wrapper: https://github.com/zmap/zgrab/blob/master/zlib/conn.go#L508.
Updated behavior matches zgrab classic.
`cmd\zgrab2\zgrab2.exe http --use-https --max-redirects 2 --heartbleed --heartbeat-enabled --timeout 3 --port 443 < alexa100.csv > alexa100.02.json`
Before, a whole mess of HeartbleedErrors got dumped. Now, they don't.

Fix heartbleed check

---

integration_tests/.template/module/scanner.go
module.go
modules/ftp/scanner.go
modules/http/scanner.go
modules/mssql/scanner.go
modules/mysql/scanner.go
modules/ntp/scanner.go
modules/postgres/scanner.go
modules/redis/scanner.go
modules/ssh.go
modules/tls.go
scanner.go
schemas/zgrab2.py

Scanners now implement a `Protocol()` method, which returns a string identifying the protocol (and more to the point, the schema for its output).
Prior to this, there is no safe way to determine the protocol that generated a piece of zgrab2 output; for simple cases the scan name is identical with the protocol, but that will not hold for scans where the default name is not used.
`make integration-test` should still work; you can confirm that in `./zgrab-output/**/*.json` the `[*].data.*.protocol` is set.
Scans with custom names will still have trouble validating, since the schema validation looks for a field named e.g. `mysql`, rather than `customName.protocol == "mysql"`.
But, since we don't allow unknown key names (even `allow_unknown` has a bug), any solution would probably require a …

Include scanner protocol in response

---

errors.go
integration_tests/pop3/cleanup.sh
integration_tests/pop3/container/Dockerfile
integration_tests/pop3/container/entrypoint.sh
integration_tests/pop3/setup.sh
integration_tests/pop3/test.sh
modules/pop3.go
modules/pop3/pop3.go
modules/pop3/scanner.go
schemas/__init__.py
schemas/pop3.py

Added POP3 module, heavily based on the original scan in ZGrab.
`TEST_MODULES=pop3 make integration-test`, or `echo "pop.mail.yahoo.com" | cmd/zgrab2/zgrab2 pop3 --pop3s --port 995 --help --quit`
No unit tests (none in the original). Threw together a dirt simple container that runs a minimalistic POP3 server with no TLS for sanity checking.
Jira task CEN-75.

zgrab2: Port POP3 module from zgrab

---

modules/imap.go
modules/imap/imap.go
modules/imap/scanner.go
schemas/imap.py

Copy existing IMAP scanning behavior from ZGrab.
No unit tests in the original, so none here.
No container here...you should be able to find an IMAP server, though:
`echo "imap.gmail.com" | cmd/zgrab2/zgrab2 imap --port 995 --imaps --send-quit`
Jira issue CEN-74

zgrab2: Port IMAP scanner from zgrab

---

lib/smb/encoder/encoder.go
lib/smb/encoder/unicode.go
lib/smb/gss/gss.go
lib/smb/gss/oid.go
lib/smb/log.go
lib/smb/session.go
lib/smb/smb.go
modules/smb.go
modules/smb/scanner.go
schemas/__init__.py
schemas/smb.py

Copied the SMB behavior from ZGrab -- namely, copied the hacked/pseudo-vendored SMB lib from zgrab/ztools/smb into zgrab2, and called its GetBanner method.
*BUT*, I have yet to have a positive hit with this (though I get the same results with the original zgrab, so maybe both my container Samba and Windows NetBIOS versions are too new).
On a host that supports SMBv1, run `echo "that-host" | cmd/zgrab2/zgrab2 smb`.
If I pull in the latest version of the SMB library (github.com/stacktitan/smb), it succeeds in detecting my test machines -- but, we would need to re-apply our hacks to give ourselves lower-level access.
Jira issue CEN-69.

zgrab2: Port SMB scanner from ZGrab

---

integration_tests/.template/module/scanner.go
modules/modbus/modbus.go
modules/modbus/scanner.go
schemas/__init__.py
schemas/modbus.py
status.go

Port the modbus scanner from zgrab.
Started by copying over the code as-is, but had to make some changes (beyond those needed to pass `golint`).
If run with the default flags, the behavior is should be unchanged (except with a different request ID) --  but some fields are now configurable, and there is an optional `strict` flag to be more selective.
No unit tests / integration tests (none in the original).
There are modbus simulators available; if using the "official" Windows one, you will need to set `--unit-id` to something other than the default of 0, otherwise it will not respond.
Jira issue CEN-72.

zgrab2: Port modbus from zgrab

---

modules/bacnet/common.go
modules/bacnet/log.go
modules/bacnet/messages.go
modules/bacnet/messages_test.go
modules/bacnet/objects.go
modules/bacnet/objects_test.go
modules/bacnet/query.go
modules/bacnet/scanner.go
schemas/__init__.py
schemas/bacnet.py

BACNet taken over directly from zgrab.
No unit tests / integration tests (none in original). Using a BACNet simulator (e.g. http://www.cbmsstudio.com/store/p11/BACnet_Simulator.html, which does not listen on the loopback interface) you can do `echo "my-address" | cmd/zgrab2/zgrab2 bacnet > out.json && python -m zschema validate schemas/__init__.py:zgrab2 out.json`.
This was written in such a way that it could be taken over from zgrab with no changes.
This represents part of Jira issue CEN-70.

zgrab2: port BACNet from zgrab

---

tls.go

Previously, you had to explicitly set `--heartbeat-enabled` in addition to `--heartbleed` for your heartbleed check to work.
This addresses that by making `--heartbleed` imply `--heartbeat-enabled`.
1. Find a heartbleed-vulnerable machine (e.g. https://censys.io/ipv4?q=443.https.heartbleed.heartbleed_vulnerable%3Atrue)
2. Run `echo "target-machine" | cmd/zgrab2/zgrab2 tls --heartbleed --port 443`
- Try before and after the fix, confirm that afterwards it comes out `"heartbleed_vulnerable":true`
Issue #91

issue #91 -- heartbleed flag implies heartbeat enabled

---

module.go

Per conversation with Zakir (and issue #94), make default timeout 10s to match zgrab behavior.
Indefinite timeout is still possible by setting an explicit timeout of 0.
```bash
nc -l -p 12345 &
echo "127.0.0.1" | cmd/zgrab2/zgrab2 telnet --port 12345
```
Before this PR, it will sit indefinitely (or until you kill the nc process); afterwards, it times out after 10s.
Brought up in discussion for #94.

Set default timeout to 10s

---

conn.go
modules/http/scanner.go

So that `--timeout` is honored even if `--use-https` is not set (issue #109).
`echo google.com | ./zgrab2 http --port 8080 --timeout 3`
Before the test, this hangs for much longer than 3s. Afterwards, it doesn't.
#109

Add a dialer for the non-TLS case in HTTP

---

modules/mssql/scanner.go
zgrab2_schemas/zgrab2/mssql.py

MSSQL currently includes the `encrypt_mode` returned by the server during prelogin (though only as a debug field), but not the actually-negotiated value.
This includes that.
** NOTE **: This requires a corresponding ES schema push.
`TEST_MODULES=mssql make integration-test`
This isn't crucial, but it would be nice to have.

MSSQL: include negotiated encrypt_mode

---

modules/postgres/connection.go
modules/postgres/scanner.go

Somewhat addresses #125 -- when a server returns syntactically-valid but unexpected postgres results, include those in the output (and stop including the debug string as was happening for ProtocolVersions).
Find some error-producing servers:
```python
results = api.search('tags.raw:"postgres" AND ServerPacket', fields=["ip", "5432.postgres.banner"])
for i in range(0, 100):
result = next(results)
if random.random() < 0.1: print result["ip"]
```
Then run the new code against them.
#125 -- this doesn't tighten the detection threshold for tagging purposes, but it does make distinguishing false positives (and perhaps different configurations) easier.

Postgres: Output format tweaks

---

modules/postgres/scanner.go
zgrab2_schemas/zgrab2/postgres.py

`_unknown_error_tag` was missing previously, and `server_parameters` is schema'd as a string.
`TEST_MODULES=postgres make integration-test`

add missing _unknown_error_tag to postgres error schema

---

zgrab2_schemas/zgrab2/postgres.py

This gets lifted out of the subrecord in other schemas, which makes it
optional in them. This is the easiest way to fix that, although it is
indicative or an underlying problem.

Make auth mode enum optional

---

lib/ssh/kex.go

in SSH kex ECDH JSONLog, don't create a field unless it's going to be populated (to allow omitempty to work properly)
`TEST_MODULES=ssh make integration-test` confirms that nothing is broken -- but we don't have a test with selectively-empty ECDH kex fields.

Omit empty values in ssh ECDH kex

---

config.go
processing.go

Rather than overloading the meaning of `--verbose` (previously defined, for better or worse, to be per-module), added a global `--debug` flag that skips stripping out the `zgrab:"debug"` output fields.
`docker run -p 33306:3306 -td --rm --name mysqltest -e MYSQL_ALLOW_EMPTY_PASSWORD=true -e MYSQL_LOG_CONSOLE=true mysql:8.0`
`make && echo "localhost" | ./cmd/zgrab2/zgrab2 mysql --port 33306 | jp data.mysql.result.auth_plugin_name`
(should be `null`: `auth_plugin_name` is debug-only)
`echo "localhost" | ./cmd/zgrab2/zgrab2 --debug mysql --port 33306 | jp data.mysql.result.auth_plugin_name`
(should be `"mysql_native_password"`, because `--debug` is enabled).
As noted in the comments, this takes advantage of the fact that `output.Process()` currently only strips the debug fields, which is a …

Add a global --debug flag to include zgrab:debug output

---

processing.go

#141 exposed the fact that zgrab2 was assuming that `ScanTarget.IP` was always being set (e.g. by looking up a hostname if that was all that was available), but that was not the case.

support ScanTarget.IP/Domain being set correctly

---

modules/ipp/scanner.go
modules/ipp/scanner_test.go
zgrab2_schemas/zgrab2/ipp.py

Correctly determines whether to include ScanResults object in output json.
Rejects successful responses which are identifiable as non-IPP.
Reduces code duplication by refactoring several re-usable segments into independent functions.
Greatly simplifies IPP zgrab2 schema by depending upon HTTP zgrab2 schema.
Future Work:
Could use further refactoring.
Add support for Upgrade to HTTPS.
N/A

(IPP) improve scan output

---

integration_tests/ipp/test.sh
modules/ipp/scanner.go
zgrab2_schemas/zgrab2/ipp.py

Fixes retry-TLS. The retry occurs if and only if the plaintext connection fails.
Collects all attributes returned in any IPP responses received.
Future Work:
Could use further refactoring.
Add support for Upgrade to HTTPS.
Add support for proper redirect handling. (Currently reporting application error for non-200 status code.)
N/A

Feature/IPP: Fix Retry-TLS and Collect All IPP Attributes

---

modules/ipp/scanner.go

Ensures that delimiter tags are handled correctly, allowing all attributes to be read.

Fix read all attributes

---

modules/ipp/scanner.go

Attempts to connect with TLS first, then falls back to plaintext if that fails. Renames option to ipps-retry rather than retry-tls
Future work:
Add an integration test based on a CUPS container that only accepts plaintext traffic, like many of the hosts encountered in the wild. This will verify that ipps-retry falls back successfully.

Try TLS before plaintext when using ipps-retry

---

zgrab2_schemas/zgrab2/ipp.py

Documents the fields of an IPP scan's results.
`make integration-test` and ensure that the validation doesn't all fall apart because the schema is broken.

IPP: document output fields

---

modules/ipp/scanner.go

Avoids problems encountered in 10^7 host scan.
IPPS-retry now works after encountering wrong status-code.
Checks bounds to avoid panic from access beyond array.

Finalize Before 1% Scan

---

zgrab2_schemas/zgrab2/ssh.py

Changes CertType's id field to Enum of strings, since an Enum of ints is not valid.
CertType SubRecords being created according to this definition were invalid, since their contained id Enum was invalid.

Corrects CertType's id's type

---

zgrab2_schemas/zgrab2/mysql.py
zgrab2_schemas/zgrab2/postgres.py
zgrab2_schemas/zgrab2/zgrab2.py

This causes problems when trying to load data into BigQuery if, for example, an entire protocol or subrecord is unpopulated.

Stop marking fields as “required”

---

zgrab2_schemas/zgrab2/postgres.py

@cdzombak noted that this was missing. Comparing this to https://github.com/zmap/zgrab2/blob/jb/addMissingPostgresErrorType/modules/postgres/scanner.go#L184, `constraint` seems to be the only field that was not present.

add missing 'constraint' field for postgres_error

---

modules/mongodb/types.go

First four bytes of mongodb message header are length of message, which includes the four byte length itself. A message of simply "\x00\x00\x00\x00" caused a zero-length buffer to be allocated and 0x00000000 attempted to be written into it. Fixed by returning an error if message length < 4, because it must at least include itself.
Run ./zgrab mongodb against server which responds to query with 4-byte 0x00000000.
```
ERRO[0000] Panic on scanner mongodb when scanning target XXX.XXX.XXX.XXX: "index out of range"
panic: runtime error: index out of range [recovered]
panic: runtime error: index out of range
goroutine 45 [running]:
github.com/zmap/zgrab2.grabTarget.func1(0xc42016e060, 0xc420352030, 0x10, 0x10, 0x0, 0x0, 0x0, 0x0, 0x16ccc6f, 0x7) …
```

Fix possible index error on malformed msg

---

modules/mongodb/scanner.go

BSON tag is case sensitive. Mongodb isMaster command responds with bool "ismaster", which we were tagging for BSON with "isMaster", causing it to be missed / always false. 
Pass IPs to zgrab of mongodb hosts which are master and not. Confirm that `is_master` is `true` when master and `false` when not.
Master:
```
"result":{"is_master":{"is_master":true,"max_wire_version":4,"max_bson_object_size":16777216,"max_write_batch_size":1000,"max_message_size_bytes":48000000,"read_only":false}}
```
Not Master:
```
"result":{"is_master":{"is_master":false,"max_wire_version":5,"max_bson_object_size":16777216,"max_write_batch_size":1000,"max_message_size_bytes":48000000,"read_only":false}}
```

BSON tag is case sensitive - s/isMaster/ismaster

---

lib/ssh/keys.go

In https://github.com/zmap/zcrypto/pull/173, the utility functions for putting the key components into a dict were removed.
This update uses functions added in https://github.com/zmap/zcrypto/pull/178 that replace this functionality.
The integration tests should pass again. (`make integration-test`)

Fix for zcrypto updates

---

modules/mongodb/scanner.go

Updated message length to account for OP_REPLY header.
Also fixed off-by-one uint32 read buffer size, but I don't think that would have broken anything.
Connect to host which responds to isMaster OP_QUERY with a reply which is longer than mongodb message header + 4 but less than that + OP_REPLY header.

MongoDB - fix isMaster message length check.

---

modules/mongodb/scanner.go

Mark build_info as `omitempty` so that zschema does not complain when it's None.
zgrab a mongodb host where isMaster succeeds but buildInfo does not
CEN-817

Omit empty build_info elm on mongodb output

---

conn.go
module.go
modules/ipp/scanner.go
processing.go

Some protocols may require more data than others.  To accomodate those,
allow the BytesReadLimit to be changed by means of BaseFlags.
By setting BaseFlags.BytesReadLimit prior to calling .Open(), scanners
can override the default limit to one that is appropriate for the data
collected.
For a protocol scanner. prior to calling `target.Open()` set `scanner.config.BaseFlags.BytesReadLimit`.  For instance:
```
func (scanner *Scanner) Scan(target zgrab2.ScanTarget) (zgrab2.ScanStatus,
interface{}, error) {
scanner.config.BaseFlags.BytesReadLimit = newMax
conn, err := target.Open(&scanner.config.BaseFlags)
[...]
}
```

Add support for BytesReadLimit parameter in BaseFlags

---

lib/mysql/mysql.go
status.go

Previously, we did sanity checking of the packet size *after* allocating / reading, potentially dumping huge data into the error string.
Now, check prior to reading, and on failure, grab some context, then fail fast.
`TEST_MODULES=mysql make integration-test`

Stricter bounds checking on MySQL

---

modules/tls.go
processing.go
tls.go

Previously, SNI was only supported with an explicit `--server-name`, which is obviously not helpful for realistic scans (see e.g. #145).
This adds new API calls that allow the `ScanTarget` (where the domain name is, when it's present) to be included when setting up the TLS connection, and updates the TLS scan module to use these them.
`echo "$(dig +short www.google.com),www.google.com" | cmd/zgrab2/zgrab2 --debug tls | jp data.tls.result.handshake_log.client_hello.server_name` -- should be "www.google.com"
`echo "$(dig +short www.google.com),www.google.com" | cmd/zgrab2/zgrab2 --debug tls --server-name www.fake-google.com | jp data.tls.result.handshake_log.client_hello.server_name` -- should be "www.fake-google.com"
`echo "$(dig +short www.google.com),www.google.com" | cmd/zgrab2/zgrab2 …

TLS SNI fixes / API cleanup

---

modules/http/scanner.go

Previous addition of GetTLSConfigForTarget (811eb38) did not modify
HTTP module to use SNI. This let to the very cryptic unknown-error:
remote error: internal error. Some servers give Fatal alerts when
they don't get an SNI extension. Discovered on a `Pagely-ARES/1.3.21`
Server. 
Currently tested manually. Examine a network capture of the following command:
`echo "https://benvds.com" | zgrab2 http`
Look at the TLS ClientHello's extensions and ensure that it includes the Extension Server Name Indication.
Only HTTP. I'm not sure the behavior of other modules that use TLS. 
Related to #147

Use Target Domain name in SNI when using HTTP

---

modules/banner.go
modules/banner/scanner.go
zgrab2_schemas/zgrab2/__init__.py
zgrab2_schemas/zgrab2/banner.py

New Banner module that can grab banner and match against a custom regexp. It will still get the banner and create protocol error  If "--pattern" is defined and the results did not match.
options:
--probe=            Probe to send to the server. Use triple slashes
to escape, for example \\\n is literal \n
(default: \n)
--pattern=          Pattern to match, must be valid regexp.
--max-tries=       Number of tries for timeouts and connection
errors before giving up. (default: 1)
echo 'google.com'|./zgrab2 banner -p 80 --pattern="asfgqwg" --probe "GET / \n\n"
Should output {"domain":"google.com","data":{"banner":{"status":"protocol-error","protocol":"banner","result":{"banner":"HTTP/1.0 .... ","error":"pattern did not match"}}}
echo 'google.com'|./zgrab2 banner -p 80 --pattern="HTTP" --probe …

Add custom regexp banner grabber

---

lib/smb/smb/session.go

The smb library bounds checks for a message size that is too large, but
does not check for a message size that is way too small.  Error out if
the message size is not at least as large as the ProtocolID 4-byte
preamble.
This fixes slice out of bound panics when checking the buffer for the
protID string for certain hosts.

SMB: Bounds check slice index before access

---

lib/smb/smb/session.go
lib/smb/smb/smb.go
lib/smb/smb/zgrab.go
modules/smb/scanner.go

There is currently no SMB1 support in the zgrab2's bundled libsmb.
This adds some rudimentary support to detect SMB1 servers, by implementing SMB1 header and SMB1 negotiation request messages.
While there is a negotiation response struct added as well, it currently is a placeholder to unmarshal into; future commits may implement unmarshal result parsing, and unmarshaling for each of the SMB1 dialects.

SMB1 Probing

---

integration_tests/.template/module/scanner.go
modules/bacnet/scanner.go
modules/banner/scanner.go
modules/dnp3/scanner.go
modules/fox/scanner.go
modules/ftp/scanner.go
modules/imap/scanner.go
modules/ipp/scanner.go
modules/modbus/scanner.go
modules/mongodb/scanner.go
modules/mssql/scanner.go
modules/mysql/scanner.go
modules/ntp/scanner.go
modules/oracle/scanner.go
modules/pop3/scanner.go
modules/postgres/scanner.go
modules/redis/scanner.go
modules/siemens/scanner.go
modules/smb/scanner.go
modules/smtp/scanner.go
modules/ssh.go
modules/telnet/scanner.go
processing.go

The port field is tied to the configuration of each instance of `Scanner` struct.  However, applications using zgrab2 scan modules may want to specify specific ports to scan, without needing to initialize a
whole new module.
This patch adds a pointer to a uint describing a port to `ScanTarget{}`. If that is not nil, the specified port will override the port in the Config.
Since the port option in the Config may not be the port currently being scanned, delete the `GetPort()` function provided by each module.
The `GetPort()` function is also not used.  While we could just change the meaning of this function, to mean "Return the port in the Config", it is probably better to go ahead and just remove all references to it as there are no users.

Allow applications to specify port via `ScanTarget{}`

---

zgrab2_schemas/zgrab2/redis.py

Fixes Small bug in the zschema for the Redis scanner, which made the field nonexistent_response required instead of nullable when generating BQ schema

fix schema in redis for nonexistent_response being required

---

modules/fox/fox.go

fox read with  io.EOF ,but the data  has been returned
testip 
113.3.143.142
37.221.240.149

fixed bug for io.EOF  on fox moudle

---

.travis.yml
go.sum
lib/ssh/handshake.go

Fixed hello-only bug to prevent key exchange sequence from entering at all if the hello-only flag is set

prevent running key exchange if hello-only flag set

---

modules/http/scanner.go
modules/ipp/scanner.go

Commit a38194a added an optional port override as part of the
scan target.  The HTTP and IPP modules, however, still compose
the URL (and select http vs https) by ignoring the override.
This checks for the override, and if present uses the scan target
port.  Otherwise, it falls back to the config port.
A) `echo hostname | zgrab2 http --use-https -p 443`
B) `echo hostname | zgrab2 http --use-https`
Run `A` should end in success, and also grab the TLS cert.
Run `B` should end in error, as it attempted against the default port 80 (assuming of course https is not running on this port on the host).
This is a bit trickier, you need a different framework other than `cmd/zgrab2` that initializes the module, and performs a scan.  However, if that is done, then if the `ScanTarget` contains a port …

Honor port override when composing URL

---

fake_resolver.go
modules/http/scanner.go

When performing HTTP scans with a domain name, we want to be able to scan that domain name with the specified IP address.  Currently, if a domain is specified, the IP address is ignored and we scan whatever the name resolves to.
This adds a fake resolver, that can be attached to a Dialer and cause the http connection to always return the IP address we  specify.  In the scanner, this also checks that the intended domain name we are about to connect to in our dialContext matches the original target domain name; if it does not, we do not attach the custom/fake resolver.
```
echo 172.217.9.78,google.com | ./zgrab2 http --port 443 --use-https
```
This should return valid results.  Replace the IP address with something like 127.0.0.1:
```
echo 127.0.0.1,google.com | ./zgrab2 http --port 443 …
```

Add the ability to use a custom (fake) DNS resolver

---

config.go
multiple.go
processing.go

Sometimes we don't know for sure, what protocol is running on some port and we want to try all supported protocols until first success. Then we can create ini file for multiple mode with the same port in all protocols, e.g.:
```ini
...
[http]
port=80
[ssh]
port=80
[ftp]
port=80
...
```
But even though http probe will probably succeed, all other specified protocols will be still tried also wasting time. For such situations it would be nice to have an option to break after first successful protocol.
So `break-on-success` option support is added.
Run multiple mode with `break-on-success` option with e.g. all supported protocols on port 80 (as in example above) for some http host e.g. icanhazip.com. Make sure no protocols are probed after successful http.
Unfortunetly we can't specify order …

add option to stop scanning host after first successful protocol

---

modules/smtp/scanner.go

this avoids to have \r\n in the error message like:
> SMTP error code %d returned from STARTTLS command (502 5.5.2 Error: command not recognized\r\n)

Trim SMTP response

---

bin/default_modules.go
bin/doc.go
module_set.go

Eventually this can be used to replace AddCommand, allowing the use of a
non-global config object.
_Add brief instructions on how to test your changes._

Add ModuleSet object

---

module.go
modules/bacnet/scanner.go
modules/banner/scanner.go
modules/dnp3/scanner.go
modules/fox/scanner.go
modules/ftp/scanner.go
modules/http/scanner.go
modules/imap/scanner.go
modules/ipp/scanner.go
modules/modbus/scanner.go
modules/mongodb/scanner.go
modules/mssql/scanner.go
modules/mysql/scanner.go
modules/ntp/scanner.go
modules/oracle/scanner.go
modules/pop3/scanner.go
modules/postgres/scanner.go
modules/redis/scanner.go
modules/siemens/scanner.go
modules/smb/scanner.go
modules/smtp/scanner.go
modules/ssh.go
modules/telnet/scanner.go
modules/tls.go

This abstracts more of the help text into the ScanModule definition,
removing some more of the need for `zgrab2.AddCommand()`
`zgrab2 help`

Add Description() to ScanModule

---

bin/bin.go
monitor.go

This updates MakeMonitor() to take the channel size as a parameter,
instead of reading it from the global `config` object. Unfortunately,
the caller of MakeMonitor() doesn't actually have access to the global,
since it's in a different package (bin vs the root package). Luckily,
there doesn't appear to be a reason to have a buffer in this channel.
This updates the caller to pass a hardcoded size of 1.
@codyprime what do you think about channel size here?

Remove reference to global config in monitor.go

---

config.go
output.go

Refactor the output handlers to take the necessary writers as arguments.
I will rebase #249 on top of this once it merges.

Remove dependency on config in output.go

---

modules/http/scanner.go

If the `--max-redirects` value is exceeded, we return `SCAN_APPLICATION_ERROR` with "Too many redirect" as the error message.
Add an option (`--redirects-succeed`) to suppress this error, and return success even if we exceed the maximum specified number of redirects.
`echo google.com | zgrab2 http --max-redirects=0`
This should show a failure status:
```
"timestamp": "2020-02-26T16:54:20-05:00",
"error": "Too many redirects"
}
{"statuses":{"http":{"successes":0,"failures":1}},"start":"2020-02-26T16:55:53-05:00","end":"2020-02-26T16:55:53-05:00","duration":"78.194261ms"}
```
With the new flag, it should succeed:
`echo google.com | zgrab2 http --max-redirects=0 --redirects-succeed`
```
},
"timestamp": "2020-02-26T16:55:12-05:00"
}
{"statuses":{"http":{"successes":1,"failures":0}},"start":"20 …
```

modules/http: Add option to suppress errors when max redirects exceeded

---

processing.go

This allows these steps to be reusable outside of the context of the
grabTarget function.
Ensure that `--debug` still works correctly.
Laying down more foundation for #249

Extract the creation and Marshal of a Grab object

---

modules/http/scanner.go

- Use `DetermineEncoding` To try and translate http bodies to UTF8 if possible. 
```
make
echo "qq.com" | ./zgrab2 http --port=443 --use-https --max-size=64 --max-redirects=5 | jq . | grep -o 腾讯首页
```
And hopefully get that a result. The chinese is the title of qq's webpage and is malformed in current results. https://censys.io/domain/qq.com
- I've tested this with some of domains from the alexa top million, but I've been unable to run a full 1% scan from `scratch-01` 
- `DetermineEncoding` returns a certainty boolean, but at least with qq it was getting the right result even though it was returning a certainty of false, so I decided to ignore it

zgrab/zgrab2: HTTP bodies getting mangled

---

lib/ssh/cipher.go
lib/ssh/cipher_test.go
lib/ssh/common.go
lib/ssh/handshake.go
lib/ssh/handshake_test.go
lib/ssh/log.go
lib/ssh/messages.go
lib/ssh/messages_test.go
lib/ssh/transport.go

Makes some the types used in the SSH scanner's result exported
Namely:
- KexInitMsg
- Algorithms
- DirectionAlgorithms

Allow for programaitc access of ssh types

---

go.mod
go.sum
modules/http/scanner.go
tls.go

So that we can advertise a slightly more expansive default set of signature/hash algorithms in the signature_algorithms extension of the TLS Client Hello, provide an option to use a pre-defined override.
This also splits up the TLS connection helper in tls.go, so that the tls.Config can be modified by a scanner module.

http/tls: Add option to override SignatureAndHashes

---

go.sum
integration_tests/postgres/setup.sh
modules/modbus/modbus.go
modules/modbus/scanner.go

- removes fatalf in `scan()`
- check message and body length in `GetModbusResponse()` 
I looked at a couple of the modbus panic logs and tested against those IPs
```
./zgrab2 modbus -p 7000 <<< 221.132.95.154
./zgrab2 modbus <<< 133.34.157.97
./zgrab2 modbus <<< 133.34.157.117
./zgrab2 modbus <<< 133.34.157.24
./zgrab2 modbus <<< 133.34.157.25
./zgrab2 modbus <<< 61.155.174.55
./zgrab2 modbus <<< 210.253.251.215
./zgrab2 modbus <<< 218.45.180.18
./zgrab2 modbus -p 3001 <<< 60.221.39.185
```

Fix panics in Modbus scanner

---

modules/ftp/scanner.go

The command line option `--implicit-tls` will attempt connecting via
TLS before intiating the FTP handshake.
You need to find a server that is using TLS around FTP (but not auth-tls or auth-ssl), and run:
`echo ip_address | zgrab2 ftp --port 990 --implicit-tls`

ftp: Add support for implicit TLS

---

modules/smtp/scanner.go

- adds a bool to the output of the smtp scanner that indicates when the connection to the server was over tls implicitly (meaning without using starttls) `implicit-tls`
```
./zgrab2 smtp --port 465 --smtps <<< 91.239.43.226 | jq .
```

adds implicit tls bool to smtp result

---

lib/http/response.go
modules/http/http_readlimit_test.go
modules/http/scanner.go

Adds a new way to compute the BodyHash for http scanner.
```
echo <ip> | ./zgrab2 http --port 443 --compute-decoded-body-hash-algorithm=sha256 | jq
"body_hash": "sha256:ff990fc95970bd2fc6333663ae043aaef308117190507bbd7b4831244cd97c2d",
echo <ip> | ./zgrab2 http --port 443 --compute-decoded-body-hash-algorithm=sha1 | jq
"body_hash": "sha1:a829c753bb3e30296c1faeea6783edf7dd23824f",
./zgrab2 http --port 443 --compute-decoded-body-hash-algorithm=md5 | jq
Invalid value `md5' for option `--compute-decoded-body-hash-algorithm'. Allowed values are: sha256 or sha1
```

Add option to compute http BodySHA256 on decoded BodyText

---

modules/ftp/scanner.go
utility.go

Port 21 on 134.223.117.55 failed an FTP scan. The buffer size in the FTP scanner was 1024, and this scan was failing because the buffer size was too small. I increased it to 10k.
https://censysio.atlassian.net/browse/DATA-970

[DATA-970] Increase buffer size in FTP scanner

---

modules/telnet/scanner.go

Even if the server does not respond to the telnet commands, the
banner may have useful information.  Add the option "--force-banner"
so that the banner string may be returned even on failure.  If the option
is not specified, the origin behavior is unchanged.

telnet: Optionally return result even on error

---

modules/http/scanner.go

improves http body decoding and enforces max length
```
echo "www.qq.com" | ./zgrab2 http -p 443 --use-https --max-size=64 --with-body-size | jq .
```
I decided the initial read should still be limited and that we should just re-enforce length afterwards, but I can see the argument for not doing that
qq.com is a good example because it decodes correctly even though it isn't certain

improves http body decoding and enforces max length

---

modules/smtp/scanner.go
modules/smtp/scanner_test.go

The SMTP module was matching on "STMP" when verifying the contents of the scan response. This PR fixes the typo and adds a test for the VerifySMTPContents() function.
`make test` and verify all tests pass.

fix for smtp module

---

config.go
output.go

This PR adds an option to flush output after each line of output. This may be desirable in streaming applications, where a program continually ingests zgrab2's output.
Run zgrab2 with the flag `--flush`. Observe that the output will be flushed after each line, rather than at the end.

Add option to flush output after each line of output

---

modules/postgres/connection.go

This happened on 32 bit with Ubuntu OS
perform tests on a host that has `sizeToRead = = 0` 
https://github.com/golang/go/issues/38673
https://stackoverflow.com/questions/27647737/maximum-length-of-a-slice-in-go
https://github.com/zmap/zgrab2/issues/288

fix issue 288

---

modules/fox/scanner.go
modules/postgres/connection.go

Fix incorrect fox service recognition
if `results == null ` but `status == "success"`
try to make request in service with `fox` flag

Fix null results in fox module

---

lib/smb/smb/encoder/unicode.go
lib/smb/smb/smb.go
lib/smb/smb/zgrab.go
zgrab2_schemas/zgrab2/smb.py

Performs session setup during SMBv1 negotiations to get these fields.
I tested this locally against [this](https://hub.docker.com/r/dperson/samba) samba image, with the settings modified to allow SMBv1 (it is disabled by default).
via `./zgrab2 smb --setup-session <<< "127.0.0.1,," | jq`:
```
{
"ip": "x.x.x.x",
"data": {
"smb": {
"status": "success",
"protocol": "smb",
"result": {
"smbv1_support": true,
"smb_version": {
"major": 1,
"minor": 0,
"revision": 0,
"version_string": "SMB 1.0"
},
"os_name": "Unix",
"ntlm": "Samba 3.0.37",
"group_name": "WORKGROUP",
"has_ntlm": false
},
"timestamp": "2020-12-10T16:20:08Z"
}
}
}
```
I also tested against various hosts in the wild, though the results aren't interesting.
Against a host that doesn't support SMBv1 or requires credentials during session …

Add NativeOS, NTLM, and GroupName to SMBv1 results

---

modules/banner/scanner.go

Read probe from file (hex probe support)
echo -e "GET / HTTP/1.1\r\n" >probe.txt
echo 'google.com'| ./zgrab2 banner -p 80 --probe-file "probe.txt"
None
https://github.com/zmap/zgrab2/issues/210

Read probe from file (hex probe support)

---

config.go
conn.go

The errors can be found by running `go vet`.
Found these issues while packaging. Somehow, these mistakes give a build failure in nixpkgs. I'm not sure why.
Check output of `go vet` before and after. I don't think these changes require much testing otherwise, zgrab2 still builds and go vet is happy now (although `go vet` still shows some other stuff, but I'm not familiar enough to fix those).

Fix incorrect logging calls that don't do formatting

---

.github/workflows/build.yml
docker-runner/runner-base.Dockerfile

Aim to address #303 by migrating from TravisCI to GitHub Actions, because many issues with TravisCI [have recently been reported](https://news.ycombinator.com/item?id=25338983).
While in PR form, the GitHub Action build results will not be visible, since this repo is currently using only TravisCI. You will need to test this PR on your own branch and push the updated branch to GitHub to see the results in the Actions tab of GitHub.
After this action is part of the repo, it will be triggered by submitting a new PR or commit. The results will be seen in the Actions tab of this repo.
**Warning**: This PR does not have full CI functionality in its initial form. The tests are currently encountering errors. I am no expert with Go build systems, so `continue-on-error: true` is used for the two …

First draft of GitHub Action

---

modules/jarm.go
modules/jarm/scanner.go

_Added JARM fingerprinting module_
```
echo $(dig +short google.com) | ./zgrab2 jarm
```
JARM is an active-fingerprinting technique developed by Salesforce.  It was released https://github.com/salesforce/jarm and a write-up on it can be found at: https://engineering.salesforce.com/easily-identify-malicious-servers-on-the-internet-with-jarm-e095edac525a
None

Added JARM fingerprinting module

---

modules/ftp/scanner.go

This pull requests adds a check in modules/ftp/scanner.go for an error upon completing a TLS handshake.

Add error handling for FTP TLS handshake

---

lib/smb/smb/encoder/encoder.go

In order for the following line,
```
r = bytes.NewBuffer(meta.ParentBuf[o : o+l])
```
to succeed, `o+l` need only be `<= len(meta.ParentBuf)`, not `<`.
This causes fields of exactly correct length to fail to unmarshal. This would not prevent a scan from being successful, but it would stop the `targetName` and `negotiateFlags` fields from being populated due to the early exit.

smb: allow dynamic length fields of exact length

---

go.mod
go.sum

Zgrab2 is failing to build on master:
```
➜  zgrab2 git:(master) make     
cd cmd/zgrab2 && go build && cd ../..
../../modules/jarm/scanner.go:7:2: no required module provides package github.com/RumbleDiscovery/jarm-go; to add it:
go get github.com/RumbleDiscovery/jarm-go
make: *** [Makefile:24: zgrab2] Error 1
```
```make``` on master

add jarm-go to go.mod

---

modules/siemens/s7.go

This MR removes the masking of errors for the siemens s7 protocol scanner. 
The current behaviour:
```
➜  zgrab2 git:(hmcguinn/s7-misidentification) ✗ echo $IP | ./zgrab2 siemens                   
INFO[0000] started grab at 2021-07-20T20:58:16-04:00    
{"ip":"$IP","data":{"siemens":{"status":"success","protocol":"siemens","result":{"is_s7":true},"timestamp":"2021-07-20T20:58:16-04:00"}}}
INFO[0001] finished grab at 2021-07-20T20:58:18-04:00   
{"statuses":{"siemens":{"successes":1,"failures":0}},"start":"2021-07-20T20:58:16-04:00","end":"2021-07-20T20:58:18-04:00","duration":"1.552316484s"}
```
The scan is marked as a success when no information is returned.
The updated behaviour:
```
➜  zgrab2 git:(hmcguinn/s7-misidentification) ✗ echo $IP | ./zgrab2 siemens         
INFO[0000] started …
```

remove masking of s7 protocols errors

---

modules/banner/scanner.go

Conversion of binary responses to UTF8 occasionally yields U+FFFD [replacement characters](https://en.wikipedia.org/wiki/Specials_(Unicode_block)) (see #197, #263 for examples). As a result it is not possible to restore the original response.
This introduces the `--hex` option to the `banner` module. When enabled, the `banner` value will contain server response in hex.
Lets grab `favicon.ico` from ur.ru:
```sh
$ echo 212.23.93.60 | zgrab2  banner -p 80 --probe 'GET /favicon.ico\n'
INFO[0000] started grab at 2021-08-20T15:47:03+05:00
{"ip":"212.23.93.60","data":{"banner":{"status":"success","protocol":"banner","result":{"banner":"\u0000\u0000\u0001\u0000\u0001\u0000\u0010\u0010\u0000\u0000\u0001\u0000\u0018\u0000h\u0003\u0000\u0000\u0016\u0000\u0000\u0000(\u0000\u0000\u0000\u0010\u0000\u000 …
```

Adds --hex option to `banner` module

---

modules/jarm/scanner.go
utility.go

This PR removes the error handling for a JARM probe response. The reason is that a handshake failure should still be processed the same as any other response. Currently a handshake failure results in the ZeroHash value being returned. This does not match the salesforce jarm module which should be treated as the correct implementation.
After this change, the salesforce and zgrab2 modules will both return the same fingerprint for services that return a handshake failure to one of the probes.
go test ./...
This PR is being created to bring the zgrab2 JARM module in line with the behavior of the salesforce jarm tool.

jarm: update jarm to not fail on handshake failure

---

modules/http/scanner.go

Fix possible http module panic 
it can happend when `io.CopyN` retrun error and `readLen != len(bodyText)`
https://pkg.go.dev/io#CopyN
Test based on http requests
https://github.com/zmap/zgrab2/issues/319

Fix http module panic

---

lib/smb/ntlmssp/ntlmssp.go

There are two errors here:
1. The offsets to the ParentBuf are not checked to be in-bounds
2. Types are uint64, but subtracted and compared to > 0.  This allows
underflow during subtraction of the size.
Unfortunately, I do not have a reproducer.  I have only seen this occur once, and have not been able to reproduce it again.
However, here is the relevant panic.  (I have omitted some lines that are sensitive, but they are not relevant)
```
runtime/debug.Stack()
/usr/local/go/src/runtime/debug/stack.go:24 +0x65
runtime/debug.PrintStack()
/usr/local/go/src/runtime/debug/stack.go:16 +0x19
github.com/zmap/zgrab2/lib/smb/ntlmssp.(*AvPairSlice).UnmarshalBinary(0xc014b78fd8, {0x117ae40, 0xc014b78fd8, 0x20c2778}, 0xc007ad0cc0)
/go/pkg/mod/github.com/zmap/zgrab2@v0.1.8-0.20210930194046-00fe9ca9af83/ …
```

smb: fix panic in ntlmssp when unmarshaling

---

modules/http/scanner.go

The HTTP module will currently fail when given IPv6 literals using standard ports (80/http and 443/https). This is because the function `getHTTPURL()` simply concatenates `proto + "://" + host + endpoint`. For non-standard ports (e.g. 8080/http), the function `net.JoinHostPort()` is used, which *will* add brackets to IPv6 literals.
1. Create a file with an IPv6 literal, e.g. `2001:558:6000:1234:5678:abcd:ef` in `input.txt`.
2. Run `./zgrab2 http -f ~/input.txt`. Observe error `"error":"parse \"http://2001:558:6000:1234:5678:abcd:ef/\": invalid port \":ef\" after host"`
3. Run `./zgrab2 http -f ~/input.txt  -p 8080`. Observe connection timeout.
4. Apply patch.  Observe connection timeout for 2.

Add brackets to IPv6 literals with standard ports in http module

---

tls.go

I would like to use `zgrab2` as a library and to pass a TLS configuration without having to serialize fields. Very important for me are:
* Root CAs
* Cipher Suites
If you know another, more elegant way, please let me know.

Add tls.Config to TLSFlags

---

lib/http/response.go
lib/http/transport.go
modules/http/scanner.go

The golang textproto library does a few things when parsing the HTTP
headers:
* consume some whitespace characters (e.g. \r\n)
* canonicalizes the header keys (e.g. "content-type" => "Content-Type")
* moves the headers into a map
This all makes sense when parsing HTTP, but for a scanner some may want
to have the exact headers, to match on order, non-canonical keys, etc.
This adds that option, if '--raw-headers' is specified during an HTTP
scan.  This is accomplished by implementing a tee reader on the pconn
interface, that tees before the bufio reader is put in place.  The
tee copy can be disabled once the headers have been read, so as to not
waste memory while consuming the HTTP body.
```
echo "8.8.8.8"  | ./zgrab2 http -p 443 --use-https --raw-headers --max-redirects=0 | \
jq -r …
```

http: allow raw header capture

---

tls.go

This is described in detail in #334 which I accidentally submitted as PR based against master. I didn't realize that the feature/TLS1.3 branch has not yet been merged
This should merge without conflict to TLS1.3
@dadrian are you handling merged to feature/TLS1.3 or is that being worked on separately? If you're the right one for the job, can you please merge this?
As always, thanks!

Change to support early TLS renegotiation (--renegotiate-freely)

---

modules/ipp/scanner.go

nameLength is used for slice allocation.  If the value is unmarshaled
as a negative value, then a runtime error will occur:
runtime error: makeslice: len out of range
(this commit also includes some minor formatting cleanup)
I have been unable to reproduce the incident I encountered again, but you can attempt scanning an IPP service found on Censys to verify there has not been a regression: 
https://search.censys.io/search?resource=hosts&sort=RELEVANCE&per_page=25&virtual_hosts=EXCLUDE&q=services.service_name%3A+IPP

ipp: nameLength should be uint16, not int16

---

modules/http/scanner.go

Use original result when retry-https encounters an error
Start with retry-https disable and find a page that redirects to a SSO page -> get a nice "Too many redirects" error.
Now enable retry-https and rescan -> you should still get the "Too many redirects" error, not a timeout or "tls oversized record received with length 20527"
Currently, whenever _any_ error is encountered and retry-https is enabled, the original, often still useful error is thrown away and instead you get either timeouts or "tls oversized record received with length 20527" when it fails, too. Especially with errors like "Too many redirects", which still can be  useful given that the body and HTTP headers are still included, this retry behavior is infuriating and harmful at best, given that the retry error usually is …

retry-https considered harmful: use original result when retry-https encounters an error

---

modules/mongodb/scanner.go

Adds the ability to retrieve database names & sizes from MongoDB.
```
for MONGO_VERSION in "2.4" "2.6" "3.2" "3.6" "4.1" "4.2" "4.4" "5.0"; do { CID=$(docker run --rm --name test-mongo -d -p 1111:27017 mongo:$MONGO_VERSION) && sleep 1 && echo -n "127.0.0.1,," | ./zgrab2 mongodb -p 1111 | jq . && docker kill $CID; } done;
```
Example output:
```
{
"ip": "127.0.0.1",
"data": {
"mongodb": {
"status": "success",
"protocol": "mongodb",
"result": {
"is_master": {
"is_master": true,
"max_wire_version": 2,
"max_bson_object_size": 16777216,
"max_write_batch_size": 1000,
"max_message_size_bytes": 48000000,
"read_only": false
},
"build_info": {
"version": "2.6.12",
"git_version": "d73c92b1c85703828b55c2916a5dd4ad46535f6a",
"sys_info": "Linux build5.ny.cbi.10gen.cc 2.6.32-431.3.1.el6.x86_64 #1 SMP …
```

Add mongodb dbnames

---

processing.go

Make it a non-fatal error when `EncodeGrab` fails to marshal data when called by `grabTarget`. Previously, if a result couldn't be encoded, the process crashed. Now, it logs an error and continues.
The proximate cause for this is https://github.com/zmap/zgrab2/issues/318 (SSH certificates with dates too large crash the process), and the workaround is due to @TrueSkrillor in that same issue. The source of the error is the go standard library's [time module](https://cs.opensource.google/go/go/+/master:src/time/time.go;drc=41b9d8c75e45636a153c2a31d117196a22a7fc6c;l=1317), and it points us to https://github.com/golang/go/issues/4556#c15. Essentially, time is trying to produce a RFC3339 string, and refuses to do so with a year that's out of range.
We began seeing this problem about the week of …

Make it a non-fatal error when EncodeGrab fails to marshal data

---

modules/smtp/scanner.go

fix typo in smtp scanner comment
No test, documentation change only
N/A
N/A

fix: typo in smtp scanner

---

modules/redis/scanner.go
modules/redis/types.go

Add TLS support for the redis module (`--use-tls`). Let me know if anything else needs to be done.
Setup a redis-server using [this configuration](https://redis.io/docs/management/security/encryption/) and run 
```
$ echo 127.0.0.1 | ./zgrab redis --use-tls -p 6379
```
Started seeing a recent trend of REDIS servers on port 6380 utilizing TLS which zgrab2 could not handle.

Add TLS support for redis

---

modules/http/scanner.go

This PR allows users to specify a HTTP request body in the `http` module via a new flag called `-request-body`
```
zgrab2 http -p 80 --method POST --request-body='{"test":"true"}' --custom-headers-names='Content-Type' --c
ustom-headers-values='application/json'
```
I needed to be able to POST a request body to fingerprint a specific webservice.
I found this [older PR](https://github.com/zmap/zgrab2/pull/339) was open, but when I tried using this fork, it didn't work
So I wrote this quickly.

feat(http-request-body): allow users to specify a request body in the HTTP module

---

lib/http/client.go
lib/http/response.go
lib/http/response_test.go

To acknowledge banners such as `HTTP/1.1 404 Not Found` (note the lack of trailing carriage returns) as HTTP, ignore EOF errors while reading headers.
_Add brief instructions on how to test your changes._

http: ignore EOF when reading headers

---

modules/fox/log.go
modules/fox/scanner.go

Added `--use-tls` flag to the FOX scanner.
Find a TLS-enabled FOX service (usually on TCP/4911), then run `zgrab2 fox --use-tls --port 4911`

Add TLS support to FOX protocol

---

modules/http/scanner.go

Add body support for invisible characters after encryption
Just use a string of hexadecimal characters as parameters
When I was testing, I found that when I encountered a request with encrypted characters that could not be displayed properly, the parameters passed through the string could not construct the same request as before.
For example, if the encrypted character is displayed as "." and I pass it as a parameter, but in reality, its hexadecimal is not 2e, it may be f8, and so on.
So at this point, we cannot simply pass in strings. We need to have the ability to pass in encrypted and invisible characters, in order to cope with which request bodies are sending miscellaneous content. (This is a problem I discovered during my research and communication with the C2 Trojan)

Add body support for invisible characters after encryption

---

lib/output/test/process_test.go
lib/ssh/kex_test.go
lib/ssh/keys_test.go
modules/fox/fox.go
modules/redis/types_test.go

* process_test swapped from golang encoding/asn1 to zcrypto
* ssh/kex_test needed Config argument for kex.Client / kex.Server
* ssh/keys_test needed the built-in dsaPublicKey
* fox.go was throwing a `go vet` warning during tests
* redis/types_test fakeIO needed additional methods to meet interface signature
```
make test
```
Fixes #387 , #388 , #389 , #390

Fixes various problems (mostly syntax) in tests

---

modules/banner/scanner.go

Hello! While using the banner module for zgrab2, there was a need for some functionality that was missing there.
I added the following:
1. calc md5, sha1 and sha256 of `body`
1. base64 encoding of an answer `body`
1. check for empty pattern
I also refactored the code a little.
Thank you!
p.s: I’m plannig to add similar functionality to the http module. Is it okay?

New functionality for zgrab2-banner: md5, sha1, sha256, base64

---

tls.go

This is driven by  #378, https://github.com/zmap/zcrypto/issues/364 and https://github.com/zmap/zgrab2/pull/334
This allows a number of scans to actually succeed, rather than fail out when parsing the certificate
Example without permissive parsing:
```
echo FAILING_IP | ./zgrab2 http -p 443 --use-https
INFO[0000] started grab at 2023-09-21T21:25:29-05:00
{"ip":"FAILING_IP","data":{"http":{"status":"unknown-error","protocol":"http","result":{},"timestamp":"2023-09-21T21:25:29-05:00","error":"tls: failed to parse certificate from server: asn1: structure error: explicitly tagged member didn't match"}}}
INFO[0001] finished grab at 2023-09-21T21:25:29-05:00
{"statuses":{"http":{"successes":0,"failures":1}},"start":"2023-09-21T21:25:29-05:00","end":"2023-09-21T21:25:29-05:00","duration":"987.606 …
```

Permissive TLS parsing

---

lib/http/client.go
lib/http/transport.go

There are many servers on the internet intending to be an HTTP service, but in reality, they do not adequately conform to the HTTP RFC. For example, many servers on the internet do not send back the full terminating CRLF or `Connection: close` headers, but we might still want to treat as HTTP, for example:
```
$ echo -ne 'GET / HTTP/1.0\r\n\r\n' | nc X.X.X.X 8085 | hexdump -C
00000000  48 54 54 50 2f 31 2e 31  20 34 30 34 20 4e 6f 74  |HTTP/1.1 404 Not|
00000010  20 46 6f 75 6e 64 0d 0a                           | Found..|
00000018
```
Note that the connection is terminated at the server-end for services like this (and lacks the proper response headers)
This patch _attempts_ to fix this single issue by catching the EOF, and if data _was_ captured in the response, do not immediately error. …

Deal with non-RFC compliant servers

---

input.go
input_test.go
processing.go

This PR allows setting a custom port in the CSV input and it also shows the port in output results.
The port number is added to the last field for backward compatibility reasons. However it's ugly when you need just IP, Port. You have to input IP,,,Port instead. You can take the target port number out in the JSON output of zgrab2 later.
Domain and port:
echo ',google.com,,80' | ./zgrab2 http
IP and port:
echo '1.2.3.4,,,80' |  ./zgrab2 http
Port number won't be shown in the output if the input was not in CSV format. For example, when using just IP or domain per line and using -p option to supply the port number.
[https://github.com/zmap/zgrab2/issues/344](https://github.com/zmap/zgrab2/issues/344)

Add port number to CSV input and output

---

README.md

Edited README.md to add installation instructions due to go get being deprecated in Go 17.

Add Install Instructions for Go v17+

---

lib/http/response.go
lib/http/transport.go
modules/http/scanner.go

See also: https://github.com/zmap/zgrab2/pull/347 
The golang textproto library does a few things when parsing the HTTP
headers:
* consume some whitespace characters (e.g. \r\n)
* canonicalizes the header keys (e.g. "content-type" => "Content-Type")
* moves the headers into a map
This all makes sense when parsing HTTP, but for a scanner some may want
to have the exact headers, to match on order, non-canonical keys, etc.
This adds that option, if '--raw-headers' is specified during an HTTP
scan.  This is accomplished by implementing a tee reader on the pconn
interface, that tees before the bufio reader is put in place.  The
tee copy can be disabled once the headers have been read, so as to not
waste memory while consuming the HTTP body.
While denoted as "raw headers", this will also …

http: allow raw header capture (#347)

---

modules/ftp/scanner.go

refactor: improve and align ftp tls error msg

---

modules/siemens/s7.go

Rewrote response parser with information provided in the issue. Resolves #212. 
Tested against some real S7 modules and _appears_ to work, absolutely makes more sense than the original code. However, would be great if we can confirm on a device we control.
Also, `ModuleId` field in `type S7Log struct` formerly reflects "Order number of the module". This behavior is kept in current version for forward compatibility but not sure if we should rename it to sth else.

Fix Parser for ModuleIdentificationRequest of s7 Protocol

---

config.go
conn.go
utility.go

resolves #419
validated that the flag works with Wireshark:

Add support for custom DNS server

---

modules/siemens/s7.go

to construct version number with major, minor, and patch from each individual bytes in Ausbg fields
as suggested in https://github.com/zmap/zgrab2/pull/423#issuecomment-2071678271

patch: getVersionNumber function

---

.github/workflows/build.yml

Adds test running to the CI step
A number of recent commits have broken tests
It would be nice if this didn't happen and the build told us.

Add test steps to build

---

lib/http/transport.go
modules/http/http_readlimit_test.go

https://github.com/zmap/zgrab2/pull/375/files caused two tests to fail:
truncate_read_header
tls_truncate_read_header
Because now we skip a block if we have EOF errors
I added a bunch of additional tests to try to confirm we'd break for a bunch of other weird cases
This turns up a potential issue where we hit an EOF and because of golang defaults, we actually return a success.
I'm not entirely sure if these are expected behavior, but minimally this highlights some perhaps unexpected side effects from the mentioned PR.

Fix tests and boundary condition

---

bin/bin.go

_Add a description of your changes here._
_Add brief instructions on how to test your changes._

fix: close CPU profile

---

integration_tests/amqp091/cleanup.sh

Noticed that there was a typo in the `cleanup.sh` script for AMQP that resulted in the containers not being cleaned up.

fixed typo in cleanup script

---

lib/ssh/messages_test.go

While investigating another PR, noticed that non-compiling code was in `messages_test.go` This fixes the formatting.
```
/opt/homebrew/opt/go/libexec/bin/go tool test2json -t /Users/phillip/Library/Caches/JetBrains/GoLand2024.1/tmp/GoLand/___TestHaSSH_in_github_com_zmap_zgrab2_lib_ssh.test -test.v -test.paniconexit0 -test.run ^\QTestHaSSH\E$
=== RUN   TestHaSSH
--- PASS: TestHaSSH (0.00s)
PASS
Process finished with the exit code 0
```

Fix non-compilation in /lib/ssh/messages_test.go

---

lib/smb/smb/smb.go

Adds support for SMB v3.0 and v3.0.2
```
$ echo "217.160.74.34"  | ./zgrab2 smb -p 445 | jq
{
"ip": "217.160.74.34",
"data": {
"smb": {
"status": "success",
"protocol": "smb",
"result": {
"smbv1_support": false,
"smb_version": {
"major": 3,
"minor": 0,
"revision": 2,
"version_string": "SMB 3.0.2"
},
```
Note: Currently excluding v3.1.1, there seems to be a bug that causes servers to reject the negotiation, rather than selecting a working version.

smb: add support for v3.0 and v3.0.2

---

.github/workflows/integration-test.yml
integration_tests/mssql/cleanup.sh
integration_tests/mssql/setup.sh
integration_tests/mssql/test.sh
integration_tests/test.sh
zgrab2_schemas/README.md

I updated zschema to run with the latest python3.12 so we can update zgrab to not require the deprecated Python2

Update zgrab's python2 dependency to python3

---

README.md

Resolves #283 
Resolves #326 
Correct guidance in `README.md` on our minimum Go version and installation instructions.
Tested with a `golang:1.15.15-buster` docker image, we no longer can build with older Go versions (to be expected since we've bumped the Go version in `go.mod`).
Tested with `golang:1.21.13-bullseye` and using the steps laid out in the README you can build with this older Go version even though we specify `Go 1.23` with the auto-downloading toolchain support they've added.

Update Golang minimum version/installation instructions

---

Dockerfile
Makefile

Before, there was an issue when trying to run a subset of the integration tests.
```
~/zgrab2 on  master! ⌚ 14:11:06
$ TEST_MODULES="amqp091" make integration-test
docker compose -p zgrab -f integration_tests/docker-compose.yml build amqp091
no such service: amqp091
make: *** [Makefile:32: integration-test] Error 1
```
The issue is that the docker containers have module_name and a version, usually.
```
$ docker compose -p zgrab -f integration_tests/docker-compose.yml config --services | grep "amqp"
amqp091-3.12.14
amqp091-3.13.2
```
This PR searches for docker containers that contain the module_name, ensuring desired behavior.

Fix issues with running subset of integration tests

---

modules/smtp/scanner.go

#509 removed flags from `SMTP` that told the module to send `EHLO`, `HELO`, and `STARTTLS` since we can infer the server's capabilities from the banner grab. However, @Seanstoppable fairly pointed out that some users may want to test if servers that don't advertise support for something in reality do.
These changes should give us sane default behavior (connect following whatever the server advertises) but allow the user to override if desired.
- add `--send-helo-override` that if enabled will send a `HELO` regardless of if the server advertises support for `ESMTP`
- add `--send-ehlo-override` that if enabled will send a `EHLO` regardless of if the server advertises support for `ESMTP`
- add `--send-starttls-override` so that regardless of if a server advertises `STARTTLS` support, we'll …

Add back in EHLO, HELO, and STARTTLS Overrides to SMTP

---

modules/banner/scanner.go

Fixed a simple SHA256 typo in the banner module, just added a missing "6"
Motivation was a need for correctly normalised data

Fix SHA256 typo

---

integration_tests/http/test.py
module.go
modules/http/scanner.go
processing.go
requirements.txt

With the module interface refactor, I overlooked that my L4 and TLS dialers were not capable of following re-directs because they used the `ScanTarget` to create the target address. If a redirect was given to some other address, it wouldn't be followed because the dialer would keep trying to dial the `ScanTarget.Host()`.
Changes
- Made the `dialerGroup.L4Dialer` aware of the input address. The two modules that use redirects (IPP and http) use this dialer. IMO, it's better to keep the `TransportAgnosticDialer` simple, it just takes in a `ScanTarget` and creates a `net.Conn` to it.
- Added a small integration test to `http` where we scan `Cloudflare.com`, `GitHub.com` and `wikipedia.org`. This test fails on `master` and these sites currently employ redirects from `http://cloudflare.com` -> …

Fix redirects not getting followed

---

Makefile
conn.go
conn_bytelimit_test.go
conn_timeout_test.go
processing.go

Handles a number of issues/inconsistencies around how we handle timeouts/contexts when dialing connections. My goal here is to have all codepaths use our `zgrab2.Dialer` and handle all connection creation there. This should both minimize the area for bugs to creep in (forgetting to set a `ReadLimit` somewhere) and also make it easier to plug in the source IP/port work.
- Before `DialTimeoutConnectionEx()` was taking in a `context.Context`, but then not using it for anything
- Our `zgrab2.Dialer` wraps a `net.Dialer`. `net.Dialer` includes a `Timeout`, so having `zgrab2.Dialer.ConnectionTimeout` is redundant. This just sets the inner `net.Dialer.Timeout` instead of having a `ConnectionTimeout`
- Small nit - felt weird that since our dialer wraps `net.Dialer`, to have it be a named field. …

Use context.Deadline in addition to specified timeouts for connections

---

README.md
modules/http/scanner.go
utility.go

Thanks to new contributor @ashleydai2003 for these suggestions!
- Adds example of using `stdin` with `echo` to `README.md`
- Adds description to `zgrab2 --help` to explain tool and give guidance on input/output + usage.
- Adds description to `http` module to give example usage
New `--help` text:
```shell
Usage:
zgrab2 [OPTIONS] <command>
zgrab2 is fast, modular L7 application-layer scanner. It is commonly used with tools like ZMap which identify "potential services", or services we know are active on a given IP + port, and these are fed into ZGrab2 to confirm and provide details of the service. It has support for a number of protocols listed below as 'Available commands' including SSH and HTTP. By default, zgrab2 will accept input from stdin
and output results to stdout, with updates and …
```

Improve ZGrab Docs/`--help`

---

lib/ssh/channel.go
modules/mssql/connection.go
modules/oracle/types_test.go
utility.go

Cleanup PR removing `min` functions since we have a built-in `min()` since Go1.21

Remove min() re-declarations

---

bin/bin.go
config.go
monitor.go
processing.go

Adds a per-second status update to `stderr` by default.
Adds a new `--status-updates-file` for users to specify if they want these updates going elsewhere.
This is very useful for making performance improvements and knowing at what rate is ZGrab scanning.
```
~/zgrab2 on  phillip/add-per-second-status! ⌚ 17:29:49
$ make; cat /tmp/10k.input | ./zgrab2 http --output-file=/dev/null --max-redirects=3  
make: Nothing to be done for 'all'.
INFO[0000] started grab at 2025-04-11T17:29:54-07:00    
00h:00m:01s; 62 targets scanned; 62.00 targets/sec; 77.4% success rate
00h:00m:02s; 95 targets scanned; 47.48 targets/sec; 67.4% success rate
00h:00m:03s; 112 targets scanned; 37.32 targets/sec; 70.5% success rate
00h:00m:04s; 134 targets scanned; 33.50 targets/sec; 74.6% success rate
...
00h:01m:28s; …
```

Add a per-second status similar to ZDNS

---

tls.go

Without this, when I'd test things with the `go run -race` race detector, these lines would flag. They are only set here, so setting in `init` should be fine and ensures it's only run once. `go run -race` had no faults after this.

Move setting global TLS parameters to init() so it's run once and -race won't complain

---

.github/workflows/integration-test.yml
conn.go
conn_timeout_test.go
utility.go

This [unit test](https://github.com/zmap/zgrab2/blob/master/conn_timeout_test.go#L404) for testing our connection timeouts in different situations has been incredibly flaky on GH runners, yet very stable on my Mac. I took a deeper look at it and noticed we were doing some weird things with timeouts.
As a background, we wrap a `net.Conn` with a `TimeoutConnection` object that we create. This lets you set various timeouts and `ctx`'s on a connection. It's vital to note, however, that a `net.Conn` only has two timeouts, a `ReadTimeout` and a `WriteTimeout`. So we need to take all of our settings and condense them into those two values by taking the minimum for them to have any effect.
- Ran 5 GH actions on the HEAD of this branch, all succeeded. So it seems stable
- Did a test HTTP scan to …

Stabilize conn timeout unit tests

---

conn.go
integration_tests/amqp091/test.sh
integration_tests/ipp/test.sh
integration_tests/mysql/test.sh
integration_tests/ntp/test.sh
module.go
modules/http/http_readlimit_test.go
modules/http/scanner.go
modules/ipp/scanner.go
modules/jarm/scanner.go
modules/ssh.go
modules/telnet/telnet.go
processing.go
scanner.go
utility.go

More info on how `master` behaves before this branch is available in the linked issue.
This PR changes the existing `--timeout` flag that strictly set timeouts on how to wait for a response to a dialed connection to two separate timeouts:
```shell
--connect-timeout=  Set max for how long to wait for initial connection establishment (0 = no timeout) (default: 10s)
-t, --target-timeout=   Set max for how long a scan of a single target (IP, Domain, etc) can take (0 = no timeout) (default: 60s)
```
I'd earlier found a server that will establish a TCP connection but not respond to a TLS handshake. A JARM probe on `master` times out after 10 mins, the previous default non-user-modifiable timeout for a target.
This branch:
```shell
~/zgrab on  phillip/526-timeouts! ⌚ 21:01:50
$ echo …
```

Make timeout behavior user-changeable and easy-to-understand

---

integration_tests/redis/container/Dockerfile

Noticed recently that the integration tests have all of a sudden starting failing on `master`, specifically on the `Redis` container.
It looks like redisv8 is under active development and v7 is the [latest released version](https://redis.io/docs/latest/operate/rs/release-notes/), so I'll pin that version.

Downgrade to using v7 of redis, since v8 is buggy right now

---

config.go
conn.go
modules/http/scanner.go
modules/mysql/scanner.go
processing.go
scanner.go
utility.go
utility_test.go
zgrab2_schemas/zgrab2/http.py

This PR does a couple things:
- ~~Changes the default DNS resolvers to a combination of Cloudflare/Google~~ Uses OS defaults
- If a user gives `--local-addr`, use that to detect IPv4/IPv6 support
- If they don't, attempt to connect to both IPv4 and v6 resolvers to self-detect. From then on, use this info to decide to use A or AAAA records during resolution
- If the user only provides the domain, we'll fill out the IP we resolve the domain to. Additionally, we'll do this outside of the modules, so if the `MULTIPLE` module is used, the target is only resolved once.
- With `http`, we have a wrinkle of complications with re-directs. I've modified the `net.Dialer` to use a custom resolver respecting our nameservers. Additionally, I've included a mapping of `resolved_names_to_ips` in the `http` …

Give user IP that domain resolves to

---

config.go

Changes
- Detect IPv4 and v6 host capability in parallel rather than sequentially
- Attempt connection to port 80 rather than port 53, should be more resilient to VPN's forcing us to use certain DNS servers
Using the below, this hangs for 2 min. on `master` with VPN enabled (Mullvad tested)
```shell
echo "example.com" | ./zgrab2 http
```
It no longer hangs with this change.
Prior to this change, we attempted to detect IPv4 and IPv6 capability by connecting to cloudflare's DNS over v4 and v6 sequentially and with the default Dial timeout of 1 min. That meant in the worst case, the user's terminal hung for 2 mins while we attempted to detect capability. This change lowers the timeout to 10s, connects in parallel, and switches to connecting to port 80, since VPNs that mess with DNS wouldn't …

Improve IP capability detection performance and over VPNs

---

Makefile
README.md

Makes the default behavior of `make` only build. This is more canonical and we still offer `make install` as an option. This forces the user to be explicit if they want to install binaries to their computer, otherwise we'll build locally in the same directory.
This reverts an earlier change I made to have `make` refer to `make install` by default.

Have default make target build, not install

---

integration_tests/http/test.py

Looks like Cloudflare starting blocking scans with ZGrab to their domain with `403 Forbidden`, so swapping `cloudflare.com` -> `docker.io`.
Fixes the integration tests failing on `master`

replace blocked cloudflare.com test with working domain

---

lib/http/request.go
modules/http/scanner.go

Adds a `SkipHost` option in `http.Request`. This skips encoding the host header, which is against the standard, but can be useful for some servers that immediately close the connection (without issuing any response) if the host header is not recognized.
Find a known HTTP server that returns an EOF error during scanning with no data received. Then issue an HTTP request with `SkipHost: true` and confirm that a 400 is returned.
This is a messy way of handling things, but some information is better than nothing at all unfortunately.

feat(http): add `SkipHost` request option

---

.github/workflows/linter.yml
Dockerfile
README.md
go.mod

With the release of Go 1.25 and following our pattern of supporting the last 2 stable releases, this PR bumps the minimum Go version to 1.24.

Bump minimum version for go to 1.24

---

modules/tls.go
processing.go

This fixes a regression added in #336455 where on TLS handshake errors, we error out. This means the user only gets an error message when they could get all the details from the host that we've already recovered.
Using the Issue opener's Shodan search, I found a couple hosts to test against and `master` definitely has the behavior they describe:
```shell
echo "192.29.83.136" | ./zgrab2-master tls                                                                                                                                                                                                                                                                     15:09:17
INFO[0000] started grab at 2025-09-22T15:23:04-07:00    
{"ip":"192.29.83.136","data":{"tls":{"status":"unknown-error","protocol":" …
```

Return all the TLS handshake details we have even if handshake fails
